package com.bookfair.backend.exception;

public enum ErrorCode {
        USER_NOT_FOUND,
        USER_DISABLED,
        USER_LOCKED,
        VENUE_NOT_FOUND,
        STALL_NOT_FOUND,
        EVENT_NOT_FOUND,
        GENRE_NOT_FOUND,
        HALL_NOT_FOUND,
        RESERVATION_NOT_FOUND,
        ORGANIZATION_NOT_FOUND,

        DUPLICATE_USERNAME,
        DUPLICATE_EMAIL,
        DUPLICATE_ORGANIZATION_NAME,

        UNAUTHORIZED,
        FORBIDDEN,

        STALL_UNAVAILABLE,
        PAYMENT_FAILED,
        PAYMENT_TIMEOUT,
        PAYMENT_DECLINED,
        RESERVATION_FAILED,
        BOOKING_EXPIRED,
        EMAIL_SEND_FAILED,
        QR_GENERATION_FAILED,
        REFUND_FAILED,

        FILE_UPLOAD_FAILED,

        VALIDATION_ERROR,
        DATABASE_ERROR,
        INTERNAL_SERVER_ERROR, 
        BUSINESS_RULE_VIOLATION, 
}
